version: "3"
services:
  node1:
    build: .
    port: 
      - 3000:3000
    logging:
      driver: "local"
      options:
        max-file: "5"
        max-size: "100m"
  node2:
    build: .
    port: 
      - 3001:3000
    logging:
      driver: "local"
      options:
        max-file: "5"
        max-size: "100m"