version: "3"
services:
  node-app1:
    build: .
    logging:
      driver: "local"
      options:
        max-file: "5"
        max-size: "100m"
  node-app2:
    build: .
    logging:
      driver: "local"
      options:
        max-file: "5"
        max-size: "100m"
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    logging:
      driver: "local"
      options:
        max-file: "5"
        max-size: "100m"